version: "3"

services:
  postgresDB:
    image: postgres:14-alpine
    container_name: postgresDB
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - "./db:/var/lib/postgresql/data"